"""Convenience imports for the wave simulation package."""

from .base import WaveSimulation
from .solvers import (
    PWaveSimulation,
    SWaveSimulation,
    SHWaveSimulation,
    SVWaveSimulation,
)
from .wave_catalog import (
    PrimaryWave,
    SecondaryWave,
    SHWave,
    SVWave,
    RayleighWave,
    LoveWave,
    LambS0Mode,
    LambA0Mode,
    StoneleyWave,
    ScholteWave,
    PlaneAcousticWave,
    SphericalAcousticWave,
    DeepWaterGravityWave,
    ShallowWaterGravityWave,
    CapillaryWave,
    InternalGravityWave,
    KelvinWave,
    RossbyPlanetaryWave,
    FlexuralBeamWave,
    AlfvenWave,
)

from .dispersion import (
    rayleigh_wave_speed,
    love_wave_dispersion,
    lamb_s0_mode,
    lamb_a0_mode,
    stoneley_wave_speed,
    scholte_wave_speed,
)
from .collage import collage_videos

__all__ = [
    "WaveSimulation",
    "PWaveSimulation",
    "SWaveSimulation",
    "SHWaveSimulation",
    "SVWaveSimulation",
    "PrimaryWave",
    "SecondaryWave",
    "SHWave",
    "SVWave",
    "RayleighWave",
    "LoveWave",
    "LambS0Mode",
    "LambA0Mode",
    "StoneleyWave",
    "ScholteWave",
    "PlaneAcousticWave",
    "SphericalAcousticWave",
    "DeepWaterGravityWave",
    "ShallowWaterGravityWave",
    "CapillaryWave",
    "InternalGravityWave",
    "KelvinWave",
    "RossbyPlanetaryWave",
    "FlexuralBeamWave",
    "AlfvenWave",
    "rayleigh_wave_speed",
    "love_wave_dispersion",
    "lamb_s0_mode",
    "lamb_a0_mode",
    "stoneley_wave_speed",
    "scholte_wave_speed",
    "collage_videos",
]
