"""Convenience imports for the wave simulation package."""

from .base import WaveSimulation
from .p_wave import PWaveSimulation
from .s_wave import SWaveSimulation, SHWaveSimulation, SVWaveSimulation
from .wave_catalog import (
    PrimaryWave,
    SecondaryWave,
    SHWave,
    SVWave,
    RayleighWave,
    LoveWave,
    LambS0Mode,
    LambA0Mode,
    StoneleyWave,
    ScholteWave,
    PlaneAcousticWave,
    SphericalAcousticWave,
    DeepWaterGravityWave,
    ShallowWaterGravityWave,
    CapillaryWave,
    InternalGravityWave,
    KelvinWave,
    RossbyPlanetaryWave,
    FlexuralBeamWave,
    AlfvenWave,
)

__all__ = [
    "WaveSimulation",
    "PWaveSimulation",
    "SWaveSimulation",
    "SHWaveSimulation",
    "SVWaveSimulation",
    "PrimaryWave",
    "SecondaryWave",
    "SHWave",
    "SVWave",
    "RayleighWave",
    "LoveWave",
    "LambS0Mode",
    "LambA0Mode",
    "StoneleyWave",
    "ScholteWave",
    "PlaneAcousticWave",
    "SphericalAcousticWave",
    "DeepWaterGravityWave",
    "ShallowWaterGravityWave",
    "CapillaryWave",
    "InternalGravityWave",
    "KelvinWave",
    "RossbyPlanetaryWave",
    "FlexuralBeamWave",
    "AlfvenWave",
]
